### ISSUE TITLE
do not set the id$ on the login entities

### ISSUE THREAD

**Issue by nherment** [senecajs/seneca-user#14]
Hi @rjrodger,

This is not super important but I'm not sure seneca-user should [set its own id$ on the login](https://github.com/rjrodger/seneca-user/blob/99b6a453985e0e0600c35900c8c217e5d6235539/user.js#L580).

It will make the login$ not work with the seneca-shard-store plugin.

In most cases we use a single in-memory store like Redis though. As this stands, it's a non-issue.

**Comment by rjrodger** [comment]
agreed - now using `token` field
