### ISSUE TITLE
SHA512 vs bcrypt

### ISSUE THREAD

**Issue by faceleg** [senecajs/seneca-user#19]
Is there a reason you've chosen to go with SHA512 here, instead of bcrypt for password hashing?

**Comment by mcdonnelldean** [comment]
@mcollina Maybe this is something you can answer, security isn't my forte. @faceleg I'd rather use whichever is more secure but I need to understand the trade-offs.

**Comment by mirceaalexandru** [comment]
@mcdonnelldean maybe we can do this pluggable? In this case it can be easy switched to whatever is required.

**Comment by mcollina** [comment]
The correct approach here is to support multiple algorithm, but store in the user model which one is selected. Basically the password is a quadruple "algorithm, algorithm options, password, salt": in the life of your app, you want to be able to upgrade those.

**Comment by mcollina** [comment]
Regarding bcrypt, the node implementation requires a native module: so I would discourage the use of that as the default. I would rather use pbkdf2 as default, I wrote https://www.npmjs.com/package/pbkdf2-password, but there are many options on NPM to have "easy" pbkdf2.

**Comment by faceleg** [comment]
I would be happy if PBKDF2 was included as a default. Note there exists a non-native bcrypt implementation: https://github.com/dcodeIO/bcrypt.js.

I don't see the point in pluggability for this feature - the module should select the most secure method and implement it, thus preventing users from choosing SHA or MD5 as they surely will - easier and familiar.

**Comment by geek** [comment]
pbkdf2 looks like a good solution... I wonder how the performance of https://github.com/dcodeIO/bcrypt.js vs the native module compares.

**Comment by mihaidma** [comment]
they claim it is 2.7 times slower

**Comment by faceleg** [comment]
There is a perf analysis: https://github.com/dcodeIO/bcrypt.js/wiki/Benchmark

I switched from the native to JS version last night, 12 rounds are slower but ... that's the point of using bcrypt/pbkdf2? if we want speed I recommend md5 :P

**Comment by mcollina** [comment]
@faceleg pluggability is needed to support upgrades of the security method. IMHO you need to be able to support multiple algorithms, but only use the best for new users.

@mihaidma using the JS version of bcrypt is a no-go for me. Being 2.7 slower would mean that an attacker is very easily 2.7 times faster than us generating it. Also, I would prefer to use something that have a lot of scrutiny for vulnerabilities (like everything that is in core) as a default.

**Comment by wzrdtales** [comment]
Agree to that, letting the package user optionally passing in his own hashing function is the best solution. Also there is nothing wrong with using SHA512 together with a reasonable amount of rounds though.

**Comment by rjrodger** [comment]
`sys:user,hook:password,cmd:encrypt` is the extension point for this - go to town!
