### ISSUE TITLE
Logout fails if token is not found

### ISSUE THREAD

**Issue by yhuiban** [senecajs/seneca-user#21]
Hello,

This simple code timeouts:
```javascript
var seneca = require('seneca')();
seneca.use('user');
seneca.ready(function () {
  seneca.act({role:'user',cmd:'logout', token: "a6d6fb1a-219f"});	
});
```

It seems the issue is at this line: https://github.com/rjrodger/seneca-user/blob/master/user.js#L687
The function returns without calling the done callback.
```javascript
      if( !login ) {
        return {ok:true}
      }
```

Perhaps should be something like:
```javascript
      if( !login ) {
        return done(null,{ok:false})
      }
```

Thanks,
Yoann

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Can confirm, happens to me too.

**Comment by mirceaalexandru** [comment]
@mcdonnelldean this is fixed as part of my PR (https://github.com/senecajs/seneca-user/pull/16), but now I am struggling to see why some tests suddenly are failing.

**Comment by mirceaalexandru** [comment]
fixed by https://github.com/senecajs/seneca-user/pull/16
