### ISSUE TITLE
Security Label

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/seneca-user#24]
A security label should be used to flag issues concerning security issues.

cf #8

**Comment by geek** [comment]
Good idea.  We have this label documented too https://github.com/senecajs/contrib/blob/master/guidelines.md#labels

**Comment by AdrieanKhisbe** [comment]
Seems like I should read deeper the Guidelines :D

**Comment by AdrieanKhisbe** [comment]
(I pang you on gitter ;))
