### ISSUE TITLE
Follow seneca style

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/seneca-user#26]
Update code to follow seneca standard: https://github.com/senecajs/eslint-config-seneca

I can take care of it once the previous PR are merge, and review completed

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe Agreed, also,

- Update Readme to match existing style better
- Add CI

**Comment by AdrieanKhisbe** [comment]
incoming very soon ;)

**Comment by AdrieanKhisbe** [comment]
in fact most of the work has been made in the refactor PRs

**Comment by mihaidma** [comment]
issues solved
