### ISSUE TITLE
Reset password should use the salt stored in user entity

### ISSUE THREAD

**Issue by jacobbubu** [senecajs/seneca-user#41]
At line https://github.com/senecajs/seneca-user/blob/master/user.js#L877

I think that should be:

```
seneca.act({ role: role, cmd: 'change_password', user: user,
            password: args.password, repeat: args.repeat, salt: user.salt },
```

**Comment by mcdonnelldean** [comment]
@mirceaalexandru can you confirm?

**Comment by mirceaalexandru** [comment]
@jacobbubu @mcdonnelldean 

I think is OK like it is now implemented. When the password is changed it is expected to change also the salt - so we do not want to use the old salt. 

So if salt is provided as part of request it will be used, if not a new salt will be generated.

**Comment by jacobbubu** [comment]
That makes sense, new password will be with a new salt.
Thanks for the response.
