### ISSUE TITLE
create salt using a seneca action

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca-user#47]
If salt will be created using a seneca action, then it will be easy to implement a custom salt generator in case this is required.

An example is when the PostgreSQL is used the salt can contain characters that are invalid for text field and because of this error occurs.

Salt can be provided explicitly as part of create_user/change_password opertions, but if the salt generator is customized it ca be easier.

**Comment by rjrodger** [comment]
options.generate_salt can be replaced with a custom function for this
