### ISSUE TITLE
"When" column should be renamed for compat

### ISSUE THREAD

**Issue by Wardormeur** [senecajs/seneca-user#51]
"when" column seems to break seneca-sqlite-store.
Considering "when" is a reserved SQL keyword, another name would be welcome to avoid such issue :)

**Comment by indr** [comment]
What about... createdAt, modifiedAt... or even better.... createdAtUtc, modifiedAtUtc etc.

**Comment by mcdonnelldean** [comment]
Is this coming from entity or specifically from seneca-user? I agree with @indr's suggestions. Thoughts @mihaidma

**Comment by rualatngua** [comment]
+1
I got the same with PostgreSQL

**Comment by mihaidma** [comment]
the seneca-sqlite-store needs to have its code replaced with the seneca-standard-store plugin. This is used by both postgres and mysql. All store fixes will go now into the standard-store plugin as it fixes all stores.

**Comment by mihaidma** [comment]
I'll close this and open an issue on both standard-store and sqlite store.
