### ISSUE TITLE
Salt shouldn't return a NULL character

### ISSUE THREAD

**Issue by Wardormeur** [senecajs/seneca-user#55]
When using the postgres connector, NULL character are not allowed, while still being generated by the salt:
`"stack": "error: invalid byte sequence for encoding \"UTF8\": 0x00\n    at Connection.parseE (/home/wardormeur/Public/CoderDojo/cp-local-development/workspace-zen/cp-users-service/node
_modules/seneca-postgresql-store/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/home/wardormeur/Public/CoderDojo/cp-local-development/workspace-zen/cp-users
-service/node_modules/seneca-postgresql-store/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/home/wardormeur/Public/CoderDojo/cp-local-development/workspace-zen/
cp-users-service/node_modules/seneca-postgresql-store/node_modules/pg/lib/connection.js:105:22)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:765
:14)\n    at Socket.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:427:10)\n    at emitReadable (_stream_readable.js:423:5)\n    at readableAddChunk (_stream_readable
.js:166:9)\n    at Socket.Readable.push (_stream_readable.js:128:10)",
 "query": {
  "text": "INSERT INTO sys_user (\"nick\",\"email\",\"name\",\"active\",\"when\",\"first_name\",\"last_name\",\"salt\",\"pass\",\"id\") values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",
  "values": [
   "g@cd.org",
   "g@cd.org",
   "tyeqfe aezfazfgeazfffffff",
   "true",
   "2016-07-21T15:58:41.977Z",
   "tyeqfe",
   "aezfazfgeazfffffff",
   "\u001a\u0000'\u001fE<>\u0002dc\u0000\u0003\u000b\u0010Cj",
   "475dd16ecfc365b9fd0bda46a7192e1acc44f919654c9ecd1b413167d79ee3a9134201465deff6ea1eea67076d7f0f796bf9e0545d6d1ed3b031ec1b1652d8a5",
   "9a0ea186-0e04-4292-8594-3449e8eafaaf"
  ]
 }`

**Comment by butlerx** [comment]
using hex instead of ascii for the salt should fix this

**Comment by rjrodger** [comment]
fixed
