### ISSUE TITLE
Missing seneca-basic dependency

### ISSUE THREAD

**Issue by jeromevalentin** [senecajs/seneca-user#72]
I'm writing an application using seneca-user as user account backend service. I'm overriding some patterns to enforce security in a custom plugin.

import Seneca from 'seneca';
let s = Seneca();
s.use('entity');
//s.use("basic");
s.use("user");
s.ready(() => {
  console.log("USER READY.... CONTINUING LOADING ")
  s.use('./plugins/my-user-service'); // This service is overriding standard seneca-user functions
...

The application was starting correcly in previous version, but upgrading to the last version
    "seneca": "^3.0.0",
    "seneca-entity": "^1.3.0",
    "seneca-mongo-store": "^1.1.0",
    "seneca-user": "^2.1.0"
lead to the following exception at startup.

Seneca Fatal Error
==================

Message: seneca: No matching action pattern found for { list:    [ { entity: '-/sys/user', fields: [Object] },     { entity: '-/sys/login', fields: [] },     { entity: '-/sys/reset', fields: [] } ],  role: 'util',  cmd: 'define_sys_entity' }, and no default result provided (using a default$ property).

Looks like the dependency to seneca-basic is no more available ... 

Uncommenting the line s.use("basic") solve the issue ... but the user plugin documentation is not up to date...

Regards,
Jérôme

**Comment by mihaidma** [comment]
Indeed seneca-basic is no longer loaded by default on seneca 3. Thank you for pointing out that the doc sample needs an update. I will do the update now.
