### ISSUE TITLE
execute_reset doesn't check password/repeat are the same

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca-user#83]
`change_password` should probably call into  `prepare_password_data` which does the extra checks and calls `encrypt_password` instead of calling into `encrypt_password` directly which is what it does now.

**Comment by killerspaz** [comment]
To add onto this, it doesn't appear `execute_reset` even verifies the existence of `password`.

I've managed to reset a user without sending `password` or `repeat` and the password was changed to `"undefined"`

**Comment by rjrodger** [comment]
fixed in new code
