### ISSUE TITLE
Security breach: Calling auth (or logout) without token can lead to { ok: true, ... }

### ISSUE THREAD

**Issue by jeromevalentin** [senecajs/seneca-user#89]
In logout (this is where I detected the issue), no test is performed to ensure that a token has been provided.

```javascript
  // Logout an existing user - resolve using token, idempotent
  // - token:    login token
  // Provides:
  // - success: {ok:true,user:,login:}
  function cmd_logout (args, done) {
    var seneca = this
    var userent = seneca.make(user_canon)
    var loginent = seneca.make(login_canon)


    var q = {id: args.token}

    loginent.load$(q, function (err, login) {
```
By providing no token in the args, the entity will load the first entity in the backend (tested with mongo). Which is not the user which is currently logging out. And the 'random user' will be logged out successfully!

The code appears to be the same in the auth implementation, which is leading to a security vulnerability.

A simple fix is just to set a default value for token (like null), to ensure the load will fail.

**Comment by rjrodger** [comment]
new version now requires a user
